### ISSUE TITLE
'make env' fails with latest core for esp32

### ISSUE THREAD

**Issue by gizero** [A-A-Milano-Smart-Park/msp-firmware#9]
```
esp32:esp32@1.0.5 installed
cp: cannot create regular file '/home/runner/work/msp-firmware/msp-firmware/var/packages/esp32/hardware/esp32/1.0.4/': Not a directory
make: *** [Makefile:119: env] Error 1
```

The error comes from the hardcoded path in `Makefile` where it automates the workaround described by [BSEC-Arduino-Library](https://github.com/BoschSensortec/BSEC-Arduino-library#3-modify-the-platformtxt-file) documentation.

According to [ESP32 core 1.0.5 release notes](https://github.com/espressif/arduino-esp32/releases/tag/1.0.5), the above issue should have been fixed in commit https://github.com/espressif/arduino-esp32/commit/9e65ed1a, but just dropping the workaround from `Makefile` does not seem to be enough. Need further investigation.

Options to fix:
* stick with ESP32 core 1.04 (pin dependency version)
* keep the workaround and make it core version-agnostic (by figuring out the correct destination path for the `platform.local.txt` file)
* hopefully drop the workaround at all...

**Comment by nor2101** [comment]
When you drop the workaround with core version 1.0.5, is the returned error different from the one you posted (I would assume a linker-related error like before the fix)?

Looking at the error report you posted it seems that the correct path is "[...]/esp32/1.0.x/", and he's trying to write to folder 1.0.4, which does not exist with version 1.0.5. So if we want to make the fix version agnostic in theory the destination path specified by Makefile should be something like "[...]/esp32/{espcore_version}/", where "{espcore_version}" is of course the esp32 core version.

If this is not doable, we should either stick to core v1.0.4 for now or drop the BSEC library altogether and move to the Adafruit BME680 lib (which is far less accurate in handling the sensor and was dropped because of that).
